name: antarctic
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - jupyter
  - click=7.1.2=py_0
  - glob2=0.7=py_0
  - keras=2.3.1
  - keras-applications
  - keras-preprocessing
  - numpy=1.16.2
  - numpy-base=1.16.2
  - numpydoc=0.9.2=py_0
  - pillow=5.4.1
  - scipy=1.2.1
  - tensorboard=1.13.1=py37_0
  - tensorflow=1.13.1
  - tensorflow-estimator=1.13.0=py_0
  - pip:
    - matplotlib==3.2.2
    - scikit-learn==0.20.2

